name: check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # Minimal version of Rust that transformrs supports.
  RUST_TOOLCHAIN: '1.81'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - run: rustup toolchain install ${{ env.RUST_TOOLCHAIN }}

      # Compile, but don't run.
      - run: cargo test --no-run

      - run: cargo test --all-features
        env:
          DEEPINFRA_KEY: ${{ secrets.DEEPINFRA_KEY }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          GROQ_KEY: ${{ secrets.GROQ_KEY }}
          HYPERBOLIC_KEY: ${{ secrets.HYPERBOLIC_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

      - run: RUSTDOCFLAGS="-D warnings" cargo doc


  typos:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: crate-ci/typos@master
        with:
          files: '.'

  fmt:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable

      - run: cargo fmt --all --check

      - run: cargo clippy -- -Dwarnings