name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        # Hardcoded commit hash to mitigate supply chain attacks.
      - uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            Notable changes since the last release are documented in the [CHANGELOG.md](https://github.com/rikhuijzer/transformrs/blob/main/CHANGELOG.md) file.
